### ISSUE TITLE
MVP data source and resources

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/terraform-provider-sonatyperepo#1]
This is a list of data-sources and resources considered to be required for the MVP of this provider:

### Data Sources
- [x] Blob Stores
   - [x] File Blob Store #3 
   - [x] S3 Blob Store #5
   - [x] Group Blob Store #5
- [x] Blob Stores - see #2 
- [x] Privileges - see #16 
- [x] Repositories - see #4
- [x] Roles - see #8
- [x] Users - see #9 

### Resources
- [x] Blob Store
   - [x] File Blob Store - see [here](https://github.com/sonatype-nexus-community/terraform-provider-sonatyperepo/commit/b4706ca64551b34580d8e716e2081123070c2b5e)
   - [x] S3 Blob Store #5
   - [x] Group Blob Store #5
- [x] System Config:
   - [x] Email - see #7 
   - [x] Sonatype IQ Server Connection see #14 
- [x] Product License - see #17 
- [x] Repository
   - [x] Maven - see #4
      - [x] Hosted
      - [x] Proxy
      - [x] Group
    - [x] NPM
      - [x] Hosted see #12 
      - [x] Proxy see #12 
      - [x] Group see #13 
- [x] Security Management
   - [x] Anonymous Access - see #10 
   - [x] LDAP Connection - see #11 
   - [x] Privileges
      - [x] Application - see #16 
      - [x] Repository Admin - see #16 
      - [x] Repository Content Selector ❌ (depends on Content Selectors for testing) - see #16 
      - [x] Repository View - see #16 
      - [x] Script ❌ (depends on phased out [Groovy Scripting](https://help.sonatype.com/en/script-api.html) disabled by default since 3.21.x) - see #16 
      - [x] Wildcard - see #16 
   - [x] Role
     - [x] Nexus Role via https://github.com/sonatype-nexus-community/terraform-provider-sonatyperepo/commit/c2560b9ee055fbc7eff93a9bfe5eab57a1e8e239
   - [x] User - see #15 

@ctownshend to contribute thoughts here.

**Comment by madpah** [comment]
Cutting MVP release `0.1.0` - FYI @ctownshend @hboutemy @Iletee @maurycupitt

**Comment by madpah** [comment]
📦 https://registry.terraform.io/providers/sonatype-nexus-community/sonatyperepo/0.1.0 has shipped.
